---
- name: Ensure gnupg is installed.
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Add PostgreSQL repository key
  block:
    - name: Add key from Postgresql site
      ansible.builtin.apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present
  rescue:
    - name: Add key from Local file
      ansible.builtin.apt_key:
        data: "{{ lookup('file', 'files/ACCC4CF8.asc') }}"
        state: present

- name: Add PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present

- name: Ensure all configured locales are present.
  community.general.locale_gen:
    name: "{{"
    state: present
    cmd: item }}
  with_items: "{{ pgsql_locales }}"
  register: locale_gen_result

- name: Ensure PostgreSQL Python libraries are installed.
  ansible.builtin.apt:
    name: "{{ pgsql_python_library }}"
    state: present

- name: Ensure PostgreSQL packages are installed.
  ansible.builtin.apt:
    name: "{{ pgsql_packages }}"
    state: present
