---
- name: Install Postgresql packages
  community.general.pkgng:
    name: "{{ pgsql_packages }}"
    state: present

- name: Install Postgresql python library packages
  community.general.pkgng:
    name: "{{ pgsql_python_library }}"
    state: present

- name: Check if PostgreSQL database is initialized.
  ansible.builtin.stat:
    path: "{{ pgsql_data_dir }}"
  register: pgdata_dir_version

- name: Ensure PostgreSQL database is initialized.
  ansible.builtin.command: /usr/local/etc/rc.d/{{ pgsql_daemon }} oneinitdb
  when: not pgdata_dir_version.stat.exists
