---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Bootstrap python for Ansible
      ansible.builtin.raw: |
        command -v python3 python || (
        command -v apk >/dev/null && sudo apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && sudo dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal)) ||
        (test -e /usr/sbin/pkg && (sudo env ASSUME_ALWAYS_YES=yes pkg update -q && sudo env ASSUME_ALWAYS_YES=yes pkg install  -q python3))
        echo "Warning: Python not boostrapped due to unknown platform."
        )
      become: true
      changed_when: false
