---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 30 7 * * 3

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: 5u623l20.pgsql

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 5u623l20.pgsql
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install test dependencies.
        run: pip3 install yamllint
      - name: Lint code
        run: |
          yamllint .

  molecule:
    name: Molecule
    runs-on: macos-12
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        distro:
          - almalinux/8
          - generic/alpine319
          - debian/bullseye64
          - ubuntu/focal64
          - generic/freebsd13
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 5u623l20.pgsql
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install test dependencies.
        run: pip3 install ansible molecule-plugins[vagrant]
      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ matrix.distro }}
          restore-keys: |
            ${{ runner.os }}-vagrant-${{ matrix.distro }}

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
